name = "nada-by-example"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/main.py"
prime_size = 128

[[programs]]
path = "src/hello_world.py"
name = "hello_world"
prime_size = 128

[[programs]]
path = "src/addition.py"
name = "addition"
prime_size = 128

[[programs]]
path = "src/subtraction.py"
name = "subtraction"
prime_size = 128

[[programs]]
path = "src/multiplication.py"
name = "multiplication"
prime_size = 128

[[programs]]
path = "src/power.py"
name = "power"
prime_size = 128

[[programs]]
path = "src/division.py"
name = "division"
prime_size = 128

[[programs]]
path = "src/modulo.py"
name = "modulo"
prime_size = 128

[[programs]]
path = "src/shift_left.py"
name = "shift_left"
prime_size = 128

[[programs]]
path = "src/shift_right.py"
name = "shift_right"
prime_size = 128

[[programs]]
path = "src/probabilistic_truncation.py"
name = "probabilistic_truncation"
prime_size = 128

[[programs]]
path = "src/comparison_lt.py"
name = "comparison_lt"
prime_size = 128

[[programs]]
path = "src/comparison_lte.py"
name = "comparison_lte"
prime_size = 128

[[programs]]
path = "src/comparison_gt.py"
name = "comparison_gt"
prime_size = 128

[[programs]]
path = "src/comparison_gte.py"
name = "comparison_gte"
prime_size = 128

[[programs]]
path = "src/if_else_public.py"
name = "if_else_public"
prime_size = 128

[[programs]]
path = "src/if_else_private.py"
name = "if_else_private"
prime_size = 128

[[programs]]
path = "src/reveal.py"
name = "reveal"
prime_size = 128

[[programs]]
path = "src/equality.py"
name = "equality"
prime_size = 128

[[programs]]
path = "src/equality_public.py"
name = "equality_public"
prime_size = 128

[[programs]]
path = "src/debug.py"
name = "debug"
prime_size = 128

[[programs]]
path = "src/for_loop.py"
name = "for_loop"
prime_size = 128

[[programs]]
path = "src/list_comprehensions.py"
name = "list_comprehensions"
prime_size = 128

[[programs]]
path = "src/list_comprehensions_with_helper.py"
name = "list_comprehensions_with_helper"
prime_size = 128

[[programs]]
path = "src/find_secret.py"
name = "find_secret"
prime_size = 128

[[programs]]
path = "src/find_secret_2p.py"
name = "find_secret_2p"
prime_size = 128

[[programs]]
path = "src/guess_value_in_matrix.py"
name = "guess_value_in_matrix"
prime_size = 128

[[programs]]
path = "src/addition_unsigned.py"
name = "addition_unsigned"
prime_size = 128

[[programs]]
path = "src/addition_public.py"
name = "addition_public"
prime_size = 128

[[programs]]
path = "src/addition_public_unsigned.py"
name = "addition_public_unsigned"
prime_size = 128

[[programs]]
path = "src/addition_literal.py"
name = "addition_literal"
prime_size = 128

[[programs]]
path = "src/addition_literal_unsigned.py"
name = "addition_literal_unsigned"
prime_size = 128

[[programs]]
path = "src/reduce.py"
name = "reduce"
prime_size = 128

[[programs]]
path = "src/voting.py"
name = "voting"
prime_size = 128

[[programs]]
path = "src/rock_paper_scissors.py"
name = "rock_paper_scissors"
prime_size = 128

[[programs]]
path = "src/random_number.py"
name = "random_number"
prime_size = 128

[[programs]]
path = "src/list_scan_linear.py"
name = "list_scan_linear"
prime_size = 128
